#!/bin/bash
# author: chuaple
# create: 2019/07/16

set -u

dir=$(cd $(dirname $0) && pwd)

link() {
    local dst=${@: -1}
    local src
    for src in "${@:1:$#-1}"; do
        ln -s -f $dir/$src $dst
        ls -l $dst/$(basename $src)
    done
}

echo Begin

link files/.[!.]* ~

link keybindings.json linux/* ~/.config/Code/User

echo Done
